### PR TITLE
updated docs

### PR DESCRIPTION
**Pull request by jdunnmon**
- [x]  small updates to `make_unipolar_matrix` to force splitting into a specific number of columns
- [x] added `pickle_model` and `unpickle_model` to `utils.py`

### CODE REVIEW

**Comment by ajratner** [comment]
Quick comments:
- `make_unipolar_matrix` is actually no longer relevant as we now learn full class-conditional accuracies
- The pickling functions are just the standard usage of `pickle`- I'd rather not add this to the repo to avoid bloat

So I think we should close this PR for now- thanks though!

**Comment by bhancock8** [comment]
Just a little more discussion on this. What if instead of making those pickle functions helpers, we just make them the default implementation of 'save' and 'load' on the classifier class? They are simple, but people do all sorts of weird things to try to load and save different object types. Might be a nice simple default option?

**Comment by ajratner** [comment]
Sure, that makes sense to me!  Let's also remove `make_unipolar`, as it's no longer necessary, that way no one gets confused

**Comment by bhancock8** [comment]
Additionally, we don't expect them to ever really be called on anything other than one of our models, so we might as well tie it in to the only object that it will see use with.

**Comment by bhancock8** [comment]
Agreed with Alex on the make_unipolar method--we've got our more sophisticated model now so no special handling required!

**Comment by jdunnmon** [comment]
I agree with Braden -- it's not obvious that pickling these will actually work (serialization errors could be weird), and I considered putting this in as the default save/load method.  I'll add these in there and remove make_unipolar.

**Comment by ajratner** [comment]
Great!

**Comment by bhancock8** [comment]
Fixed by 8f25caa60bea1bec935bf6bd826f9d79568c818e

**Pull request closed without merging**
