### PR TITLE
Replace MetalDataset with Pytorch's TensorDataset

### PR DESCRIPTION
**Pull request by tridao**
MetalDataset seems to do the same thing. Might as well use the Pytorch's one.

### CODE REVIEW

**Comment by tridao** [comment]
Nevermind. I see you're passing both torch.Tensor and np.ndarray into the end model.

**Comment by ajratner** [comment]
This is a great kind of issue to raise though (looking where custom code can be replaced with existing libs / fns) so thank you!!!

**Comment by tridao** [comment]
`make check` failed on Travis, with seemingly unrelated errors. It passes on my local copy.

**Comment by ajratner** [comment]
My main comment is that I'd like to avoid shifting any burden onto the user whenever possible- even if it's just making them have to transform everything into `Tensors`.  Also, in our current design docs, we've settled on `numpy` input / output by default, since still more standard.

A compromise might be to just make the definition of `MetalDataset` simpler, by making it just a simple wrapper for `TensorDataset` that ensures the input `X,Y` are tensors, then just creates a `TensorDataset`?

**Comment by tridao** [comment]
If you want to stick with np.ndarray then the existing `MetalDataset` is fine.

**Comment by ajratner** [comment]
Cool thanks!

**Pull request closed without merging**
