### PR TITLE
Torch saving loading

### PR DESCRIPTION
**Pull request by ajratner**
@jason-fries I think this approach of just using torch instead of pickle to save and load the whole object should work---it does on CPU with simple test---but can you check that it works for the CPU/GPU mapping case?

If it doesn't work, then may have to save/load the model object and `state_dict` (buffers and Parameters) separately...

### CODE REVIEW

**Comment by bhancock8** [comment]
Cool. And torch.save uses python's pickle for serialization anyway, and can also store non-torch objects like dicts, etc., so it shouldn't be too different. For posterity's sake, what was the problem that you ran into @jason-fries that this is solving?

**Comment by jdunnmon** [comment]
I think the major issue is that if you pickle a model that has stored .cuda() weights and try to load it on the CPU you get an error -- @jason-fries correct me if I'm wrong.

**Comment by jason-fries** [comment]
@jdunnmon is right.  I was training models on the GPU but loading them elsewhere on CPU. `torch.load` can handle that remapping as outlined here https://discuss.pytorch.org/t/on-a-cpu-device-how-to-load-checkpoint-saved-on-gpu-device/349

**Comment by bhancock8** [comment]
Cool. With your thumbs up then, @jason-fries, we'll merge it in.

**Comment by ajratner** [comment]
@jason-fries ready to merge then?

**Comment by jason-fries** [comment]
Yup!

**Pull request merged**
